<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Politická Strana DNG</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="page1" class="page blue">
        <button class="button red" onclick="navigateTo('page2')">Přejít</button>
    </div>

    <div id="page2" class="page red hidden">
        <button class="button black back" onclick="navigateTo('page1')">Zpět</button>
        <button class="button blue" onclick="navigateTo('page3')">O nás</button>
        <button class="button blue" onclick="navigateTo('page4')">Členové</button>
        <button class="button blue" onclick="navigateTo('page5')">Program</button>
    </div>

    <div id="page3" class="page hidden">
        <button class="button black back" onclick="navigateTo('page2')">Zpět</button>
        <p>Politická strana DNG byla založena Štěpánem Procházkou, Šimonem Krátkým a Oliverem Sobčákem 12.11. 2024.</p>
    </div>

    <div id="page4" class="page hidden">
        <button class="button black back" onclick="navigateTo('page2')">Zpět</button>
        <ul>
            <li>Šimon Krátký</li>
            <li>Štěpán Procházka</li>
            <li>Oliver Sobčák</li>
        </ul>
    </div>

    <div id="page5" class="page hidden">
        <button class="button black back" onclick="navigateTo('page2')">Zpět</button>
        <p>Ještě není k dispozici.</p>
    </div>

    <script src="script.js"></script>
</body>
</html>

body {
    margin: 0;
    font-family: Arial, sans-serif;
}

.page {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100vh;
    text-align: center;
}

.hidden {
    display: none;
}

.blue {
    background-color: #0000ff;
    color: #ffffff;
}

.red {
    background-color: #ff0000;
    color: #ffffff;
}

.black {
    color: #000000;
    background-color: #ffffff;
    border: 2px solid #000000;
}

.button {
    padding: 10px 20px;
    margin: 10px;
    font-size: 16px;
    cursor: pointer;
    border: none;
    border-radius: 5px;
}

.red {
    background-color: #ff0000;
    color: #ffffff;
}

.blue {
    background-color: #0000ff;
    color: #ffffff;
}

.black.back {
    position: absolute;
    top: 20px;
    left: 20px;
}

function navigateTo(pageId) {
    // Hide all pages
    document.querySelectorAll('.page').forEach(page => {
        page.classList.add('hidden');
    });

    // Show the selected page
    document.getElementById(pageId).classList.remove('hidden');
}
